import React, { useState, useRef, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link, useNavigate } from 'react-router-dom';
import { Mail, Phone, User, ArrowLeft, School, Search, X } from 'lucide-react';
import { supabase } from '../lib/supabaseClient';


const WaitlistForm = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    university: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [isAlreadyRegistered, setIsAlreadyRegistered] = useState(false);
  
  // States for custom dropdown
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const dropdownRef = useRef<HTMLDivElement>(null);

  // List of universities for the dropdown
  const universities = [
    "Aakash International Business Management College",
    "Abaya School of Nursing",
    "Abbas Khan College for Women",
    "Abhaya College of Nursing",
    "Abhudaya Degree College Sarjapur Road",
    "Academy of Business Management Tourism & Research",
    "Acharaya Polytechnic",
    "Acharya B M Reddy College of Pharmacy",
    "Acharya College of Education",
    "Acharya College of Imaging Technology",
    "Acharya College of MHA",
    "Acharya College of MLT",
    "Acharya College of Nursing",
    "Acharya Institute of Graduate Studies",
    "Acharya Institute of Health Sciences",
    "Acharya Institute of Management and Science",
    "Acharya Institute of Physiotherapy",
    "Acharya Institute of Technology",
    "Acharya ITI (Bommasandra)",
    "Acharya ITI (Peenya)",
    "Acharya Patashala College of Arts and Science",
    "Acharya Patashala College of Commerce",
    "Acharya Pathashala Rural College of Engineering (Somanahalli)",
    "Acharya School of Design",
    "Acharya School of Law",
    "Acharyas Bangalore B School",
    "Acharya's N R School of Nursing",
    "Acharyas NRV School of Architecture (Soladevanahalli)",
    "Achutha Institute of Technology",
    "ACS College of Engineering",
    "Adarsh Institute of Management & Information Technology",
    "Adarsha College Of Nursing",
    "Adarsha Film & TV Institute",
    "Adarsha Polytechnic",
    "Adarsha Vidyakendra College of Nursing",
    "Adithya Institue of Management Studies & Resarch",
    "Aditya Academy of Architecture & Design",
    "Aditya Bangalore Institute of Pharmacy \nEducation and Research",
    "Adventist College of Nursing",
    "AECS Maaruti School of Nursing",
    "AECS Maruthi College of Dental Sciences",
    "AECS Maruthi College of Nursing",
    "Agragami Institute of Computers & Advanced Management Studies",
    "Agragami Vidya Kendra",
    "Aishwarya Institute of Management Studies",
    "Aishwarya School of Nursing",
    "AJ College of Nursing",
    "Akash Institute of Medical Sciences & Research Centre",
    "Akkamahadevi School of Nursing",
    "Akshara first Grade College",
    "Akshya College",
    "Akson Academy College",
    "Al Khateeb Polytechnic",
    "Al-Ameen Arts  science & Commerece College  (Hosur Road)",
    "Al-Ameen College of Education",
    "Al-Ameen College of Law",
    "Al-Ameen College of Pharmacy",
    "Al-Ameen Institute of Information Science",
    "Al-Ameen Institute Of Management Studies",
    "All India Institute of Local Self Government",
    "Alliance Business  Academy",
    "Alliance College of engineering and design (Chikkahagade)",
    "Alliance school of law (Chandapura)",
    "Alliance School Of Management",
    "Al-Mighty First Grade College",
    "Alpha College of Engineering",
    "Ambedkar College of Education",
    "Ambigara Chowdaia College of Education",
    "Ambigara Chowdaiah College of Nurisng",
    "Ambika College of Nursing",
    "Ambika School of Nursing",
    "AMC College of Engineering",
    "AMC Degree College (Bannerghatta)",
    "Amitha College Of Education",
    "Amrita School of Engineering",
    "Amrutha Hospital & Training Center",
    "Amrutha Institute of Engineering & Management Sciences",
    "Animaster Academy College of Animation",
    "Anthem Biosciences Pvt Ltd",
    "Anugraha B Ed College(SVS College of Education)",
    "Anupama College of Education",
    "Anupama College of Management and Science",
    "Anupama School of Nursing",
    "Anuradha School of Nursing",
    "Apoorva Institute of Management Studies",
    "Apparals Designers Academy",
    "APS Polytechnic",
    "AR Institute of Paramedical College",
    "Army Institute of Fashion & Design",
    "Army Institute of Hotel Management & Catering Technology",
    "Arunodaya College",
    "Arunodaya Institute of Legal Studies",
    "ASC Degree College",
    "ASC Silver Valley Degree College",
    "Ashoka Polytechnic",
    "Ashwini School of Nursing",
    "Asian Institute of Gaming & Animation",
    "Atma College",
    "Atreya Ayurvedic Medical College",
    "Atria Institute of Technology",
    "AVK School of Nursing",
    "Azim Premji University  (Hosur Road)",
    "Azim Premji University  (Sarjapur Main Road)",
    "B W Lions Super Specialty Eye Hospital",
    "Baghirathi Bai Narayana Rao Mane College",
    "Baldwin Methodist College",
    "Baldwin Polytechnic",
    "Baldwin Womens Methodist College",
    "Banasawadi College of Nursing",
    "Bangalore  Medical College (OTT)",
    "Bangalore Baptist College Of Nursing",
    "Bangalore City College",
    "Bangalore City College of Education",
    "Bangalore City College of Nursing",
    "Bangalore City School of Nursing",
    "Bangalore College of Education",
    "Bangalore College of Engineering & Tech",
    "Bangalore College of Management Studies",
    "Bangalore Institute of  Nursing",
    "Bangalore Institute of Dental Sciences & Hospital",
    "Bangalore Institute of Legal Studies",
    "Bangalore Institute of Management Studies",
    "Bangalore Institute of Technology",
    "Bangalore Instiute of International Management",
    "Bangalore Instiute of Management Studies",
    "Bangalore International College",
    "Bangalore Management College",
    "Bangalore Medical College",
    "Bangalore School of Interior Design",
    "Bangalore Technological Institute",
    "Bangalore University (Deparment of microbiology & Biotechnology)",
    "Bangalore University (Department of Architecture)",
    "Bangalore University (Department of Coumputer Science & Application )",
    "Bangalore University (Department of Life Science)",
    "Bangalore University (Department of Management)",
    "Bangalore University (Department of Mathematics)",
    "Bangalore University (Department of Sociology)",
    "Bangalore University (Department of Zoology)",
    "Bangalore University (MCA)",
    "Bapu College of Education",
    "Bapu College of Management Studies",
    "Bapu Degree College",
    "Basavashree College of Law",
    "Basaveshwara College of Arts Science and Commerce",
    "Basaveshwara College of Education",
    "Basaveshwara Degree College",
    "BBMP First Grade College  (Kasturaba Nagar)",
    "BBMP First Grade College For Women (Frazer Town)",
    "BBMP First Grade College (Magadi Road)",
    "BBMP Women First Grade College (Byraveshwara Nagara)",
    "BEL First Grade College",
    "Bengaluru Central University, Central College",
    "Bengaluru Dr BR Ambedkar School of Economics",
    "Bengaluru Institute Paramedical Sciences",
    "Bengaluru Law College",
    "BES College of Education",
    "BES College of Law",
    "BES Degree College",
    "BES Institute of Pharmacy",
    "BES Institute of Technology",
    "BET College of Management and Science",
    "BET Sadathunnisa Degree College",
    "Bethel International College of Commerce",
    "BGS Global Institute of Medical Sciences",
    "BGS Polytechnic",
    "Bhagath College of Nursing",
    "Bhagavan Buddha First Grade College of Arts and Commerce",
    "Bhagawan Mahaveer Jain College of Nursing",
    "Bhagwan Buddha Homoeopathic  Medical College & Hospital",
    "Bharath Education Society Teachers Training \nInstitute",
    "Bharath Matha Womens College",
    "Bharatheeya Samskrithi Vidyapith Commerce College",
    "Bharathiya Samskruti Vidyapitha Arts & Science",
    "Bharatiya Vidya Foundation College",
    "Bheema Chandra Paramedical Institute",
    "Bhuvan College of Nursing",
    "Bhuvan ITI",
    "Bhuvan Law College(Venkatala)",
    "Bhuvan Polytechnic",
    "Bhuvan School of Nursing",
    "Bhuvana New College",
    "Bibi Fathima ITI",
    "Bilhara Academy of Nursing Sciences",
    "Bilwaa ITI",
    "Bishop Cotton Academy of Professional Management",
    "Bishop Cotton Women Christian Law College",
    "Bishop Cotton Women College",
    "BJR College of Nursing",
    "BMA College of Arts,  Science and Commerce",
    "BMS  College of Law",
    "BMS  Hospital College of Nursing",
    "BMS College for Womens",
    "BMS College of Architecture",
    "BMS College of Commerce and Management",
    "BMS College of Engineering",
    "BMS Hospital Nursing School",
    "BMS Institute of Technology",
    "BMS School of Architecture",
    "BNES First Grade College",
    "BNM Degree College",
    "BNM Institute of Technology",
    "Bowring & Lady Curzon Hospital Nursing School",
    "Brilliant College",
    "Brindavan College",
    "Brindavan College of Engineering",
    "Brite College of Nursing",
    "Brite Institute of Management & Science (AVK Bright First Grade College)",
    "Brite School of Nursing",
    "BSBS Business Academy",
    "BSF Institute of Technology",
    "BSV Degree College",
    "BTL First Grade College",
    "BTL Institute of Technology Management",
    "BTL ITI",
    "BTL Polytechnic",
    "BTM First Grade College",
    "BVK Shraddha School of Nursing",
    "Cambridge Institute of Technology",
    "Cambridge Institute of Technology (North Campus)",
    "Canara Bank School of Management Studies (K R Circle)",
    "Capitol Teachers Training College",
    "Cauvery B Ed College",
    "Cauvery First Grade College",
    "Cavalier Animation and Media College",
    "CB Bandari Jain College",
    "Center for Management Studies Jain University",
    "Centre of Soft Matter Research",
    "CES Institute of Fashion Technology",
    "Chaitanya School of Nursing",
    "Chamarajpet First Grade College",
    "Charans Degree College",
    "Chetana Lalitakala Mahavidyalaya",
    "Chinai College of Nursing",
    "Chinai School of Nursing",
    "Chinmaya Institute of Management",
    "Chinmaya Institute of Nursing",
    "Chinnamma Junjappa  Reddy RJS College",
    "Chitrakoota Institute of Information Sciences",
    "Christ  Deemed to be University (Kengeri)",
    "Christ Academy Institute For Advanced Sudies",
    "Christ Academy Institute of Law",
    "Christ College of Science and Management",
    "Christ Deemed to be University (Hulimavu)",
    "Christ Deemed to be University (Suddeguntepalya)",
    "Christ the King College",
    "Christian College of Nursing",
    "Christian Institute of Management",
    "Church of South India Goodwill Polytechnic",
    "Church of South India Hospital",
    "City College",
    "City Engineering College",
    "CMA B Ed College",
    "CMR Centre for Business Studies",
    "CMR Centre for Media Studies",
    "CMR College of Education",
    "CMR College of Nursing",
    "CMR College of Pharmacy",
    "CMR Institute of Management Studies",
    "CMR institute of Technology",
    "CMR Law School",
    "CMR School of Nursing",
    "CMR University",
    "CNK College of Nursing",
    "CNK Institute of Business Management",
    "CNK Reddy College of Business Management",
    "College of Horticulture",
    "College of Nursing St. Martha's Hospital",
    "Colombia College",
    "Colombia College of Nursing",
    "Command Hospital",
    "Community Institute of Commerce & Management Studies",
    "CREO Valley College",
    "Creo Valley School of Film & Television",
    "Crescent First Grade College for Women",
    "CSI Goodwill Polytechnic For Women",
    "CSI Hospital",
    "CV Gurukul College of Commerce",
    "CV Gurukula College",
    "D A Pandu Memorial R V Dental College",
    "Dairy Science College",
    "Darshan College",
    "Dayanand Sagar College of Journalism",
    "Dayanand Sagar College of Pharmacy",
    "Dayanand Sagar University School of Basic & Applied Sciences",
    "Dayananda College of Paramedical Sciences",
    "Dayananda Sagar Academy of Technology & Management",
    "Dayananda Sagar Business Academy",
    "Dayananda Sagar College of Arts",
    "Dayananda Sagar College of Dental Sciences",
    "Dayananda Sagar College of Engineering",
    "Dayananda Sagar College of Nursing",
    "Dayananda Sagar College of Physiotherapy",
    "Dayananda Sagar Institute of Technology",
    "Dayananda Sagar School of Nursing",
    "Dayananda University",
    "Devanga Sangha First Grade College",
    "Dhanvantari Nursing College",
    "Dhanvanthri College of Management & Science",
    "Dhanvanthri School of Nursing",
    "Dhanwantri College of Education",
    "Dharmasagara First Grade College",
    "Diamond College of Management and Science",
    "Diana College of Education",
    "Diana College of Management Studies",
    "Diana College of Nursing",
    "Diana School of Nursing",
    "District Institute of Education and Training",
    "Divyajyothi ITC",
    "Don Bosco College of Science and Management",
    "Don Bosco institute of Bio Science",
    "Don Bosco Institute of Technology",
    "Don Bosco School of Management",
    "Dr Ambedkar Degree College",
    "Dr Ambedkar Institute of Management",
    "Dr Ambedkar Institute of Technology",
    "Dr B R Ambedkar Institute of Paramedical Science",
    "Dr B R Ambedkar Medical College",
    "Dr BR  Ambedkar Law College",
    "Dr BR Ambedkar Institute of Nursing",
    "Dr John's College of Nursing",
    "Dr John's School of Nursing",
    "Dr MC Modi Eye Hospital Institute of \nParamedical Sciences",
    "Dr MH Krishna Institute of Indology",
    "Dr NSAM First Grade College",
    "Dr Rammanohar Lohia College of Law",
    "Dr S Gopalaraju Government First Grade College",
    "Dr Shyamala Reddy College of Nursing",
    "Dr Shyamala Reddy Dental College",
    "Dr Shyamala Reddy School of Nursing",
    "Dr SR Chandrashekar Institute of Speech and Hearing",
    "Dr Sri Sri Sri  Shivakumara Mahaswamy Polytechnic",
    "Dr Sri Sri Sri Shivakumara Mahaswamy College of Engineering",
    "EARTHA-Elements of Art and Heritage Academy",
    "East Point College of Engineering & Technology",
    "East Point College of Engineering for Women",
    "East Point College of Mangement",
    "East Point College of Medical Sciences and Research Centre",
    "East Point College of Nursing",
    "East Point College of Pharmacy",
    "East West College of  Management",
    "East West College of Engineering",
    "East West College of Nursing",
    "East West College of Paramedical Sciences",
    "East West College of Pharmacy",
    "East West First Grade College of Science",
    "East West Institute of Polytechnic",
    "East West Institute of Technology",
    "East West Polytechnic",
    "East West School of Nursing",
    "Easy Education College",
    "Eben Ezer College of Nursing",
    "Eben Ezer School of Nursing",
    "Ebenezer College",
    "ESIC college of Nursing",
    "ESIC Medical College",
    "Eurindian Academy of Hotel Management",
    "Faith British Academy",
    "Faith College of Nursing",
    "Faith Institute of Nursing Sciences",
    "Fame India Academy",
    "Faran College of Management",
    "Faran College of Nursing",
    "Faran School of Nursing",
    "FAS First Grade College",
    "Father Mathews College of Nursing",
    "Fatima (D Ed) Teachers Training Institute For \nWomen",
    "Federal College of Management",
    "Federal College of Nursing",
    "Florence College of Nursing",
    "Florence College of Physiotherapy",
    "Florence Degree College",
    "Florida College of Education",
    "Florida College of Nursing",
    "Florida School of Nursing",
    "Fortis institute of Medical Sciences (Banneraghatta Road)",
    "Frank College of Education",
    "Full-in-Faws College",
    "Ganga Kaveri Institute of Science & Management",
    "Gangothri College of Nursing",
    "Garden City College of Nursing",
    "Garden City College of Physiotherapy",
    "Gateway College of Business Management",
    "Gautham College of Pharmacy",
    "Gayathri College of Nursing",
    "Gayathri Devi College of Nursing",
    "Gayathri Institute of Nursing Sciences",
    "Gayathri Institute Of Paramedical Sciences",
    "Gayathri School of Nursing",
    "GB College of Nursing",
    "GEAR BEd College",
    "GEAR School of Graduate Studies",
    "GEF Institute of Optometry",
    "General Hospital Jayanagar",
    "Ghousia College of Engineering",
    "Ghousia ITI (Muneshwara Temple)",
    "Ghousia Polytechnic for Women",
    "GIBS Business School",
    "Giridhar Ramanarayan Institute of Commercial Practice",
    "Gitam Deemed to be University (Nagadevanahalli)",
    "GKVK Agriculture college",
    "Global Academy of Technology",
    "Global College Of Management Studies",
    "Global College of Management Studies",
    "Global College of Nursing",
    "Global Institute for Corporate Education",
    "Global School of Nursing",
    "GM College of Education",
    "Gold Finch College of Nursing",
    "Gold Finch School of Nursing",
    "Golden Institute of Nursing Science",
    "Goodwill Christain Womens College",
    "Gopalan College of Commerce (K R Puram)",
    "Gopalan College of Engineering & Management",
    "Gopalan School of Architecture & Planning",
    "Goutham College Of Allied Health Sciences",
    "Goutham College of Education",
    "Goutham College of Nursing",
    "Goutham College of Paramedical Sciences",
    "Goutham College of Physiotherapy",
    "Goutham college of science",
    "Goutham Institute of Nursing",
    "Gouthami College of Nursing",
    "Gouthami School of Nursing",
    "Government  College of Nursing",
    "Government Arts College (K R Circle)",
    "Government Ayurvedic Medical College",
    "Government College of Pharmacy (Subbaiah Circle)",
    "Government Dental College",
    "Government Engineering College (Ramanagara)",
    "Government Film & T V Technical Institute  (Hesaraghatta)",
    "Government First Grade College",
    "Government First Grade College  (Rajajinagar 2nd Block)",
    "Government First Grade College (Bidadi)",
    "Government First Grade College (Chikkaballapura)",
    "Government First Grade College (Devanhalli)",
    "Government First Grade College (Doddaballapura)",
    "Government First Grade College (Frazer Town)",
    "Government First Grade College (Harohalli)",
    "Government First Grade College (Hesaragatta)",
    "Government First Grade College (Hoskote)",
    "Government First Grade College (Jayanagar)",
    "Government First Grade College (K.R. Puram)",
    "Government First Grade College (Kadugudi)",
    "Government First Grade College (Kengeri)",
    "Government First Grade College (Malleswaram)",
    "Government First Grade College (Nelamangala)",
    "Government First Grade College (Peenya)",
    "Government First Grade College (Ramanagara)",
    "Government First Grade College (Sulibele)",
    "Government First Grade College (Thyamagondlu)",
    "Government First Grade College (Varthur)",
    "Government First Grade College (Vemagal)",
    "Government First Grade College (Vijayanagar)",
    "Government First Grade College for Women (Doddaballapura)",
    "Government First Grade College Near (Yelahanka)",
    "Government First Grade College(HSR Agara)",
    "Government Homoeopathic Medical College",
    "Government ITI  BT Centre (Peenya)",
    "Government ITI (Anekal)",
    "Government ITI (Devanahalli)",
    "Government ITI (Doddaballapura)",
    "Government ITI (Doddadunnasandra)",
    "Government ITI (Domlur)",
    "Government ITI (Harohalli)",
    "Government ITI (Nelamangala)",
    "Government ITI (Ramanagar)",
    "Government ITI (Shidlaghatta)",
    "Government ITI (Tumkur Road)",
    "Government ITI (Women)",
    "Government ITI (Women)",
    "Government Law College (Ramanagara)",
    "Government Model ITI (Hosur Road)",
    "Government Polytechnic (Channasandra)",
    "Government Polytechnic (Immadihalli)",
    "Government Polytechnic (Ramanagara)",
    "Government R C College (Race Course Road)",
    "Government R C Institute of Business Management (K R Circle)",
    "Government School of Nursing K C General Hospital (Malleshwaram)",
    "Government School of Nursing Victoria Hospital",
    "Government Science College (Nrupathunga Road)",
    "Government SKSJ Technological Institute (K R Circle)",
    "Government Tool Room & Training Centre",
    "Government Tool Room & Training Centre(ETC/MTC) (Rajajinagar)",
    "Government Tool Room & Training Centre(PDTD)(Rajajinagar)",
    "Government Unani Medical College",
    "Government Womens Polytechnic",
    "Government womens polytechnic (Ramanagara)",
    "Gowtham College of physiotherapy (Mahalakshmi Layout)",
    "GR College of Arts  Science & Commerce",
    "Green Mountain College",
    "GRR College of Nursing",
    "GRV Business Management Academy",
    "GS ITI (College Rd, Hosakote)",
    "GS ITI (Pillagumpe, Hosakote)",
    "GT Institute Management Studies & Research",
    "GT Institute of Advanced Studies",
    "Gupta College(BSK 3rd Stage)",
    "Gurukul Education & Management Studies",
    "Hamsalekha Desi Vidya Samsthe",
    "Harsha College of Nursing",
    "Harsha Institute of Allied  Health Sciences",
    "Harsha Institute of Paramedical Sciences",
    "Harsha Institute of Physiotherapy",
    "Harsha School of Nursing",
    "Harward Institute of Management & Science",
    "Hasanath College",
    "Hasnath Academy of Management Studies",
    "Hasnath College for Women",
    "Havanur College of Law",
    "HCG college of Allied health Sciences",
    "Heera College of Commerce",
    "HEHS Institute of Para Medical Sciences(Amruthahalli)",
    "HEHS Institute of Para Medical Sciences(Doddaballapura)",
    "HHS & HMS ITI",
    "Hill Side Ayurveda Medical College And Hospital",
    "Hill Side College of Nursing",
    "Hill Side College of Pharmacy",
    "Hill Side Institute of Management",
    "Hill Side School of Nursing",
    "Hina College of Nursing",
    "Hina School of Nursing",
    "Hindustan Aviation Academy",
    "Hindustan Business School",
    "Hindustan Business School (Chennappanahalli)",
    "Hindustan Electronic Academy Polytechnic",
    "HKBK College of engineering",
    "HKBK Degree College (KSMF First Grade College)",
    "HKES Veerendrapatil Degree College",
    "HMR Chickkagullappa Education Trust (R)",
    "HMR School of Nursing",
    "Holy Mother Institute of Nursing",
    "Hosakote Mission Institute of Nursing",
    "Hosmat College of Nursing",
    "Hosmat College of Physiotherapy",
    "Hosmat Education Institute of OTT",
    "Hosmat Institute of Medical Sciences",
    "IBMR International Business School",
    "IBMT College of Graduate Studies",
    "ICAT Design and Media College",
    "ICBIO  Clinical Research PVT LTD",
    "ICFAI Business School (IBS business School)",
    "IFIM College",
    "IFIM Law College",
    "IIFA Education Trust",
    "IIFA Lancaster Degree College",
    "Ikon Nursing College",
    "Impact College of Engg & Applied Science",
    "Impact Polytechnic",
    "Impact School of Architecture",
    "Indian Academy College of Nursing",
    "Indian Academy School of Management Studies",
    "Indian Academy School of Nursing",
    "Indian Academy Degree College",
    "Indian College of  Nursing",
    "Indian Institute of Astrophysics",
    "Indian Institute of Ayurvedic Medicine & Research",
    "Indian Institute of Fashion Technology",
    "Indian Institute of Nursing (Rajarajeshwari Nagara)",
    "Indian Institute of Plantation Management",
    "Indian Institute of Psychology and Research",
    "Indian Institute of Science (IISc)",
    "Indian Instiute of Psycology",
    "Indian Plywood Industries Research & Training Institute",
    "Indian School of Nursing",
    "Indian Statistical Institute",
    "Indira Gandhi College of MLT",
    "Indira Gandhi College of Nursing",
    "Indira Priyadarshini School of Nursing",
    "Indo Asian Academy Degree College",
    "Indo Asian Womans Degree College",
    "Indus Valley Degree College",
    "INIMS College",
    "Innova Institute of Management And Science",
    "Inspire Institute of Science and Commerce",
    "Institute of Aerospace Medicine",
    "Institute of Bioinformatics",
    "Institute of Health Management Research",
    "Institute of Hotel Management",
    "Institute Of Nephro-Urology",
    "Institute of Printing Technology",
    "Institute of Social and Economic Change",
    "Govt. Institute of Textile Technology",
    "Institute of Wood Science & Technology",
    "Intech Institute of Business Management",
    "International Academy of Management  & Entrepreneurship",
    "International College of Science and Information",
    "International Institute of Business Studies",
    "International Institute of Hotel Management (IIHM)",
    "International School of Fashion Arts and Design",
    "International School of Management Excellence",
    "IR POLYTECHNIC",
    "ISBR College",
    "ISBR Law College",
    "Islamia Niswan Degree College for Women",
    "Islamiah Institute of Technology",
    "IZEE Business School",
    "IZEE College of Management & Information Science",
    "J P School of Nursing",
    "Jain (Deemed-to-be University) Centre for Management Studies  (Lalbagh Road)",
    "Jain (Deemed-to-be University) School of Computer Applications & IT (Jayanagar 9th Block)",
    "Jain (Deemed-to-beUniversity) (V V Puram)",
    "Jain (Deemed-to-beUniversity) Center for Post Graduate Studies (Jayanagar 3rd Block)",
    "Jain (Deemed-to-beUniversity) CMS Business School (J P Nagar 6th Phase)",
    "Jain (Deemed-to-beUniversity) Faculty of Management Studies  (Gandhi Nagar)",
    "Jain (Deemed-to-beUniversity) School of Graduate Studies  (J C Road )",
    "Jain (Deemed-to-beUniversity) School of Humanities and Social Science (Palace Road)",
    "Jain College (RR Nagar)",
    "Jain College (V V Puram)",
    "Jain Institute Of Business Management (Jakkasandra)",
    "Jain University (Jakkasandra)",
    "Jame-Ul-Uloom College of Information Science",
    "Jame-UL-Uloom ITI (Bannikuppe)",
    "Janatha First Grade College",
    "Jayadeva Institute of Cardiology",
    "JCS ITI",
    "JD Institute of Fashion of Technology",
    "JES Mother Teresa College of Nursing",
    "Jindal First Grade College for Women",
    "Jnana Jyothi College of Business",
    "Jnana Jyothi Degree College",
    "Jnana Jyothi School of Nursing",
    "Jnana Mandira Degree College",
    "Jnana Vikas Institute of Management Studies And Commerce",
    "Jnana Vikas Institute of Technology",
    "Jnanaganga Degree College",
    "Jnanapeetha Degree College",
    "Jnanesh Institute of Nursing",
    "Josco College of Nursing",
    "Joshi Institute of Paramedical Sciences",
    "Joshi School of Nursing",
    "JSS Academy of Technical Education",
    "Jubilee College",
    "Jubilent Biosys Limited",
    "Jupiter College of Nursing",
    "Jupiter School of Nursing",
    "Jyothi Nivas college",
    "Jyothy Institute of Technology",
    "Kairalee Nikethan Degree College",
    "Kairalee Nikethan Golden Jubilee Degree College",
    "Kalabhyraveshwara Polytechnic",
    "Kalamandira School of Arts",
    "Kamala College of Management Studies",
    "Kamala College of Nursing",
    "Kamala Krishna Royale Nursing College",
    "Kamala School Of Nursing",
    "Kammavari Sangh Group & Institutions",
    "Kanaka College of Management Studies and Science",
    "Karnataka Chitrakala Parishath",
    "Karnataka College of Education",
    "Karnataka College of Management & Science",
    "Karnataka College of Nursing",
    "Karnataka College of Pharmacy",
    "Karnataka Institute of Leather Technology",
    "Karnataka Remote Sensing Application Centre",
    "Karnataka Samskrit University",
    "Karnataka School Of Nursing",
    "Karunya First Grade College",
    "Kaveri First Grade College",
    "Kempegowda College of Nursing",
    "Kempegowda Institute of Management Studies & Research",
    "Kempegowda Institute of Medical Sciences",
    "Kempegowda Institute Of Nursing Sciences",
    "Kempegowda Institute of Physiotherapy",
    "Kempegowda Law College",
    "Ken Kalashale",
    "Kengeri First Grade College",
    "Keshava College of Dance & Music",
    "Kidwai Memorial Institute of Oncology",
    "KIET B Ed College",
    "KIET Polytechnic",
    "Kiran College of Nursing",
    "KK College of Commerce & Management",
    "KKECS B Ed College",
    "KKECS College Of Pharmacy",
    "KKECS Institute of Mangagement and Computer Science",
    "KKMP ITI",
    "KLE College of Pharmacy",
    "KLE Society Law College",
    "KLE Society S Nijalingappa College",
    "KLE Society’s Institute of Dental Sciences",
    "KLE Society's Degree College",
    "KMJ College Of Nursing",
    "KNN College of Nursing",
    "KNN School Of Nursing",
    "KNS Institute of Technology",
    "Koshys College of Nursing",
    "Koshys Institute of  Management Studies",
    "Koshys School Of Nursing",
    "KR college of Nursing",
    "KR College of Pharmacy",
    "KR Institute Of Health Sciences",
    "KR School Of Nursing",
    "Kreda School Of Nursing",
    "Krishnadevarayan College of Dental Sciences",
    "Krishnasagara D Ed college",
    "Kristu Jayanti College",
    "Kristu Jayanti College of Law",
    "Krupanidhi College of Commerce & Management",
    "Krupanidhi College of Nursing",
    "Krupanidhi College of Pharmacy",
    "Krupanidhi College of Physiotherapy",
    "Krupanidhi Education Trust School Of Nursing",
    "Krupanidhi First Grade College",
    "Krupanidhi Institute Of Nursing",
    "KS Institute of Technology",
    "KS Polytechnic",
    "KS School of Engineering and Management (KSSEM)",
    "KTG Ayurvedic Medical College And Hospital",
    "KTG College of Management & Science",
    "KTG College of Nursing Sciences",
    "KTG College of Physiotherapy",
    "KTG School Of Nursing",
    "KTSV First Grade College For Women",
    "Kuvempu First Grade College",
    "KVT Polytechnic",
    "Lady Vailankanni Degree College",
    "Lakshmi Devi School Of Nursing",
    "Lalbahadur Shastri College of Education",
    "Lavanya College of Education",
    "LBS  Govt First Grade College",
    "Lisaa School Of Design",
    "LNR Degree College",
    "Lohits Academy Of Commerce",
    "LORAA Business Academy",
    "Lorven Education Centre",
    "Lorven International Institute of Management Studies",
    "Lorven School Of Nursing",
    "Lourds College of Education",
    "Lowry Memorial College",
    "Loyola Degree College",
    "Loyola ITI",
    "M Basavaiah Institute of Management Studies",
    "Maaruti College Of Dental Sciences & Research Centre",
    "Magnum First Grade College",
    "Mahalakshmi School Of Nursing",
    "Maharani Arts Commerce and Management College for Women",
    "Maharani Lakshmi Ammani  Womens College",
    "Maharani Science College",
    "Maharishi Institute of Management",
    "Maharshi Savitha College of Education",
    "Mahatma Gandhi Professional College of Nursing",
    "Mahatma Gandhi Professional School Of Nursing",
    "Mahatma Gandhi School Of Nursing",
    "MAJ School Of Nursing",
    "Malleshwaram Ladies Association FGC",
    "Mallige College of Nursing",
    "Mallige College of Pharmacy",
    "Mallige Medical Centre",
    "Manasa College of Management",
    "Mangala Instititue of Management Studies",
    "Mangalore Institute of Fire & Safety Enginnering",
    "Mangalore Institute Of Management And Science",
    "Manjunatha School Of Nursing",
    "Manjushree College of Nursing",
    "Mannu Polytechnic",
    "Mariam School Of General Nursing And Midwifery",
    "Mariyappa First Grade College",
    "Maruthi College of Dental Sciences and \nResearch Centre",
    "Mary Matha School Of Nursing",
    "Mathrusri Ramabai Ambedkar College of Nursing",
    "Matru School Of Nursing",
    "MATS Institute of Management & Entrepreneurship",
    "Maulana Azad National Urdu University ITI",
    "MCEBTI ITI",
    "Megha Centre for Electronics and Biomedical \nTechnology of India-ITI",
    "MEI Polytechnic College",
    "MES College of Arts",
    "MES College of Pharmacy",
    "MES First Grade College (BTM Layout)",
    "MES Instiute of Management",
    "MES Teachers college",
    "MEWA Degree College",
    "Milind Institute of Pharmacy",
    "Miranda College",
    "Miranda College Of Education",
    "Miranda College of Nursing",
    "Miranda School of Nursing",
    "MJ Adarsha Nursing School",
    "MLA Academy of Higher Learning",
    "MN Degree College",
    "MN Technology Institutute",
    "Mobility India",
    "Modern Institute Of Nursing",
    "Mont Fort College",
    "Mother Teresa College of Education",
    "Mother Teresa School Of Nursing",
    "Mother Theresa B Ed College",
    "Mother Theresa College of  Nursing",
    "Mother Theresa College of Management & Science",
    "Mount Carmel College",
    "Mount Mallari ITI",
    "MP Birla Institute of Management",
    "MQI Degree College",
    "MR Ambedkar Dental College & Hospital Institute",
    "MR College of Nursing for Women",
    "MS  Ramaiah Institute of Nursing",
    "MS Engineering College",
    "MS Ramaiah College of Arts Science & Commerce",
    "MS Ramaiah College of Education",
    "MS Ramaiah College of Hotel Management",
    "MS Ramaiah College of Law",
    "MS Ramaiah College of Pharmacy",
    "MS Ramaiah Dental College",
    "MS Ramaiah Institute of Applied Sciences",
    "MS Ramaiah Institute of Management",
    "MS Ramaiah Institute of Nursing Sciences",
    "MS Ramaiah Institute of Technology",
    "MS Ramaiah Medical College",
    "MS Ramaiah Polytechnic",
    "Muslim Orphanage ITI",
    "MVJ College of Education",
    "MVJ College of Engineering",
    "MVJ College of Nursing",
    "MVJ Medical College & Research  Hospital",
    "MVJ Polytechnic",
    "MVJ School Of Nursing",
    "MVM ITI",
    "MVM Suma College of Nursing",
    "MVM Suma Institute Of Nursing Sciences",
    "My Institute Aided D.Ed College",
    "Nadgir Evening Polytechnic",
    "Nadgir Institute of Engineering & Technology",
    "Nadgir Polytechnic",
    "Nagarajuna Degree College",
    "Nagarathna Srikantiah Paramedical College",
    "Nagarjuna College of Engineering & Technology",
    "Nagarjuna College of Management Studies",
    "NAISH College (Naseema Fareed Institute of Speech & Hearing)",
    "Nalanda College of Education",
    "Narayana Hrudayalaya College of Nursing",
    "Narayana Hrudayalaya School of Nursing",
    "Narayana Hrudyalaya Instiute of  Physiotheropy",
    "Narayana Hrudyalaya Instiute of Medical Science",
    "Nargund College of Pharmacy",
    "Nargund Degree College",
    "Naseema Institute of Optometry and Research",
    "National Areospace Laboratories",
    "National Ayurveda Dietetics Research Institute Government Central Pharmacy Annexe Ashoka Pillar Jayanagar",
    "National Bureau of Agriculturally Important Insects",
    "National College (Jayanagar)",
    "National College  (Basavanagufi)",
    "National College of Nursing",
    "National Institute of Advanced Studies",
    "National Institute of Fashion Technology",
    "National Institute of Mental Health and Neuro \nSciences",
    "National Institute of PG Studies in Hindi",
    "National Skill Training Institute for Women",
    "Natya Institute of Kathak and Choreography",
    "Navaneetham School of Nursing",
    "Navodaya School of Nursing",
    "NC Patel School of Nursing",
    "Nethaji ITI",
    "Nethradhama School of Ophthometry",
    "Netrajyothi College of Health Sciences",
    "New Baldwin International Degree College",
    "New Horizon College (Devarabisanahalli)",
    "New Horizon College (Kasturinagar)",
    "New Horizon College of Education",
    "New Horizon College of Engineering",
    "New Sarvodaya School of Nursing",
    "New Shores International College",
    "New Sri Shanthini College of Nursing",
    "NIAM College of Management Studies",
    "Nightingale College Of Nursing",
    "Nightingale School of Nursing",
    "NIMS Management Institutions",
    "Nirmal Jyothi Technical Institute",
    "Nirmal Jyothi Technical Institute",
    "Nirmala School of Nursing",
    "Nisarga Degree College",
    "Nitte Institute of Technology",
    "Nitte Research and Education Academy",
    "Nitte School of Architecture",
    "NITTE School of Fashion Technology & Interior Design",
    "NMKRV Collge for Women",
    "Nobel Institute of Business Excellence",
    "Noble School of Business",
    "Noor College of Nursing",
    "Noor School of Nursing",
    "Notre Dame Junior College of Education",
    "NRI Institute",
    "NSS Institute Of Paramedical Sciences (Kuduregere)",
    "NSVK Sri Venkateshwara Dental College & Hospital",
    "NSVK Trust",
    "NTTF (Electronic City)",
    "NTTF Pvt ITI",
    "NU Trust College",
    "Oceanik College of Higher Education",
    "Om Prabha FGC Womens College",
    "Om Sai Degree College",
    "Oriental College of Nursing",
    "Osteen College",
    "Oxbridge Business School",
    "Oxbridge College of Science & Commerce",
    "Oxford College of Arts",
    "Oxford College of Pharmacy",
    "Oxford Degree College",
    "Oxford School of Nursing (B B Road)",
    "Oxford School of Nursing (J P Nagar)",
    "Oxford Teachers Training Institute",
    "P E S School of Engineering",
    "Padma College of Management & Science",
    "Padmashree College of Hospital Management",
    "Padmashree Institute of Clinical Research",
    "Padmashree Institute of Information Science",
    "Padmashree Institute of Management & Sciences",
    "Padmashree Institute of Medical Lab Technology",
    "Padmashree Institute of Nursing",
    "Padmashree Institute of Physiotherapy",
    "Padmashree School of Public Health",
    "Panchajanya Vidhya Peetha Degree College",
    "Panchami College of Law",
    "Panchasheela Degree College",
    "Panchasheela Polytechnic",
    "Patel Institute of Science & Management",
    "Patel Law College",
    "Patel School of Nursing",
    "Pavana College of Nursing",
    "Pavana School of Nursing",
    "PES College",
    "PES College of Pharmacy",
    "PES Degee College (Electronic city)",
    "PES Degree College of Education",
    "PES Institute of Technology",
    "PES Polytechnic",
    "PESIT South Campus",
    "Pinnacle Institute of Management & Science",
    "Pinnacle Institute of Nursing Sciences",
    "PMS School of Nursing",
    "PNS Womens Institute of Technology",
    "PR College of Nursing",
    "Pragathi First Grade College (Chikkabanavara)",
    "Pragathi First Grade College (Vijayapura)",
    "Pragathi Institute of Nursing",
    "Pragathi ITI",
    "Pragathi ITI (Vijayapura)",
    "Pragathi Womens College",
    "Prajwal College of Nursing",
    "Prashasthi Degree College",
    "Prayukthi International College",
    "Presidency College of Nursing",
    "Presidency Degree College (Hebbal)",
    "Presidency School of Nursing",
    "Presidency University",
    "Pride Degree College",
    "Priyadarshini School of Nursing",
    "Professional Instiute of Management Studies",
    "Province College",
    "PVP ITI",
    "PVP Polytechnic",
    "Quality College of Management Studies & Science",
    "Quality Health Care College of Nursing",
    "Quality Health Care School of Nursing",
    "Radiance College",
    "Radiance College of Management & Science",
    "Rai Technology University",
    "Raja Rajeswari  School of Nursing",
    "Raja Rajeswari (Para)Medical College & Hospital",
    "Raja Rajeswari Dental College & Hospital",
    "Raja Rajeswari Medical College & Hospital",
    "Rajadhani Degree College",
    "Rajajinagar College of Education",
    "Rajajinagar First Grade College",
    "Rajajinagar Parents Association FGC",
    "Rajalakshmi ITI",
    "RajaRajesheshwari College of Engineering",
    "Rajarajeshwari College of Nursing",
    "Rajarajeshwari College of Physiotherapy",
    "Rajiv Gandhi College of Dental Science & \nHospital",
    "Rajiv Gandhi College of Law",
    "Rajiv Gandhi College of Nursing",
    "Rajiv Gandhi Institute of Technology",
    "Rajiv Gandhi Polytechnic",
    "Ramaiah Institute of Business Studies",
    "Ramaiah Institute of Management Studies",
    "Ramakrishna Ayurvedic Medical College",
    "Ramakrishna School of Nursing",
    "Raman College of Pharmacy",
    "Raman ITI",
    "Raman Polytechnic",
    "Raman Research Institute",
    "Ramanashree Academy of Management",
    "Ranebennur Taluk Education Society's College of Nursing",
    "Rani Sarala Devi Degree College",
    "Ranjani College of Performing Arts",
    "Ravindranath Tagore School of Nursing",
    "RBANMS First Grade College",
    "RCD College of Management and Information \nTechnology",
    "Regional College Of Management",
    "Regional Institute of Co-operative Management",
    "Regional Institute of English B Ed English College",
    "RES Polytechnic",
    "Research & Development",
    "Reva First Grade College",
    "Reva Institute of Engineering & Technology",
    "Reva Institute of Science & Technology",
    "Reva Institution of Management Studies",
    "Reva University",
    "RJS First Grade College",
    "RJS Polytechnic (Koramangala)",
    "RL Abhishek Rao College of Nursing",
    "RL Jalappa Industrial Training Centre",
    "RL Jalappa Institute of Technology",
    "RL Jalappa Polytechnic",
    "RL Jallapa ITC",
    "RNS First Grade College",
    "RNS Institute of Technology",
    "Roohi College of Nursing",
    "Roohi School of Nursing",
    "Rosy Royal College of Allied Health Sciences",
    "Rosy Royal Homoeopathic Medical College and \nHospital",
    "Rosy Royal International College of Physiotherapy",
    "Royal Academy for Management Studies",
    "Royal College of Arts, Science and Management",
    "Royal College of Nursing",
    "Royal Concorde School of Nursing",
    "RR College of Education",
    "RR College of Management Studies and Comp Application",
    "RR College of Nursing",
    "RR College of Pharmacy",
    "RR Institute of Adavanced Studies",
    "RR Institute of Management",
    "RR Institute of Medical Sciences",
    "RR Institute of Technology",
    "RR Polytechnic",
    "RR School of Architecture",
    "RR School of Nursing",
    "RS College of Management and Science (Doddajala)",
    "RT Nagar Degree College",
    "RT Nagar School of Nursing",
    "Ruman School of Nursing",
    "RV (Rashtreeya Vidyalaya) Teachers College",
    "RV College of Architecture",
    "RV College of Engineering",
    "RV College of Nursing",
    "RV College of Physiotherapy",
    "RV Institute of Legal Studies",
    "RV Institute of Management",
    "RVD College of Management & Information Technology",
    "Sacred Degree College (Ganapathihalli)",
    "Sacred Hearts Girls First Grade College(Jeevanbheemanagar )",
    "Sacred Hearts Teachers Training Institute (East End Jayanagara)",
    "Sadhana Degree College",
    "Sahakaari Vidyakendra Polytechnic",
    "Sai Vidya Institute of Technology",
    "Sainik School of Nursing",
    "Sambhram Institute of Technology",
    "Sambram Academi of Management Studies",
    "Sampurna Montfort B Ed College",
    "Samruddhi PU & Degree College (Pethanahalli Gate)",
    "SAM'S College Of Management Studies",
    "Samvaad College of Speech and Hearing",
    "Sanjay  Gandhi Accidental Hospital & Research Center",
    "Sanjay Gandhi college of Education",
    "Sanjay Gandhi Institute of Trauma & Orthopaedics College of Allied Health Sciences",
    "Sankara College of Optometry",
    "Sapthagiri College of Engineering (Bagalagunte)",
    "Sapthagiri Institute of Medical Sciences and research centre",
    "Sardar Vallabai Patel First Grade College (Sarjapur)",
    "Sarojini College of Nursing",
    "Sarojini School of Nursing",
    "Sarvodaya College of Education",
    "Sarvodaya College of Nursing",
    "Sarvodaya First Grade College",
    "Sarvodaya Law College",
    "SB College of Education (Yelahanka New Town)",
    "SB College of Hospital Administration",
    "SB College of Management Studies (Yelahanka New Town)",
    "SB College of Nursing",
    "SB School of Nursing",
    "School of Regenerative Medicine",
    "SCT College of Education",
    "SCT College of Nursing",
    "SCT Institute of Technology",
    "SCT Polytechnic",
    "SDM Institute of Ayurveda and Hospital",
    "SDS TRC & RGICD College of Nursing",
    "SEA College of  Arts  Science & Commerce",
    "SEA College of Education",
    "SEA College of Engineering & Technology",
    "SEA College of Nursing",
    "SEA ITI",
    "SEA School of Nursing",
    "Seribiotech Research Laboratory  Central Silk Board Ministry of Textile Kodathi",
    "Seshadripuram Institute of Management Studies",
    "Seshadripuram Law College",
    "SET Degree College (Sarvodaya Education Trust) (Agrahara Dasarahalli)",
    "SGR Polytechnic",
    "Shakuntala Devi International Institute  of Management Science",
    "Shankara College of Optometry",
    "Shankthiniketan Polytechnic College",
    "Shanthi Dhama School of Nursing",
    "Shanthini Kethana College",
    "Shanti Dhama College",
    "Shanti Dhama College of Nursing",
    "Shantiniketan College of Education",
    "Shantiniketan Polytechnic College (Ramanagar)",
    "Sharada Vikas Institute of Management Studies",
    "Sharada Vikas School of Excellence for Law",
    "Sharadadevi College of Nursing",
    "Sha-Shib College",
    "Shekar College of Nursing",
    "Shekhar Institute of Nursing",
    "Sheshadhripuram First Grade College",
    "Sheshadripuram Arts  Science & Commerce College",
    "Sheshadripuram Commerce College",
    "Sheshadripuram Institute of Commerce & Management",
    "Sheshdripuram Academy of Busienss Studies",
    "Shifaa School of Nursing",
    "Shree Bhavani School of Nursing",
    "Shree Krishna Degree College",
    "Shri Balaji College of Law (K H B Colony)",
    "Shri Jagadguru Renukacharya College of Law",
    "Shri Pillappa College of Engineering",
    "Shri Sharada First Grade College",
    "Shri Veerabhadraswamy ITI (Vibhuthipura)",
    "Shri Vidya Vinaya Institute Of Technology",
    "Shushruti College of Education",
    "Shushruti College of Nursing",
    "Shushruti Institute of Business Management",
    "Shushruti School of Nursing",
    "Shushruti School of Nursing",
    "Shuttariya College of Education",
    "Siddaganga College of Management and Science",
    "Sidvin School of Business Management",
    "SIET College",
    "Silicon City College (KR Puram)",
    "Silicon City College of Management and Commerce",
    "Sindhi College of Commerce",
    "Sir M Vishveshwaraiah college",
    "Sir M Visvesvaraya First Grade College(Konena Agrahara)",
    "Sir M Visvesvaraya Institute of Technology (Hunasamaranahalli)",
    "Sivananda Sarma Memorial RVCollege (SSMRV)",
    "SJB College of Education",
    "SJB College of Management Studies",
    "SJB College of Nursing",
    "SJB Institute of Technology",
    "SJB School of Architecture & Planning",
    "SJB School of Nursing",
    "SJC Institute of Technology",
    "SJES College Education",
    "SJES College of Hotel Mangament",
    "SJES College of Mangament Studies",
    "SJES College of Nursing",
    "SJES Polytechnic",
    "SJES School of Nursing",
    "SJM Polytechnic (Nelamangala)",
    "SJP First Grade College",
    "SJR Women College",
    "SJRC Arts  Science and Commerce College",
    "Skites Degree College",
    "SKM Teachers College",
    "Skybird Aviation",
    "SLN College of Arts Commerce (KR Market)",
    "SLN First Grade College",
    "SLN Teachers Training Instiute",
    "Smt Gangamma Hombegowda First Grade College",
    "Smt Kamala Bai Degree College",
    "Smt Lakshmi Devi College of Nursing",
    "Smt Mehras College of Education",
    "Smt Mehra's College of Management Studies & Science",
    "Smt Nagarathanamma College of Nursing",
    "Smt Nagarathnamma School of Nursing",
    "Smt Nalini Raghunath Rao Degree College (Jigani)",
    "SN Bhat College of Commerce & Business Management",
    "Sneha College of Nursing",
    "Sofia College of Nursing",
    "Sophia Degree College (K G halli)",
    "Soundarya Institute of Management & Science",
    "South Asia Institute of Advanced Christian Studies",
    "Spurthy College of Nursing",
    "Spurthy College of Science & Management Studies",
    "Spurthy Institute of Nursing",
    "SRC Institute of Business Management",
    "Sree Balaji Degree College",
    "Sree Cauvery Management College (Kodihalli HAL 2nd Stage)",
    "Sree Omkar College of Commerce & Management",
    "Sree Srinivasa Industrial Training Centre",
    "Sree Srinivasa ITI",
    "Sree Venkateshwara School of Nursing",
    "Sri  Anupama Degree College",
    "Sri  K Shivaram ITC",
    "Sri Adi Chunchanagiri College of Business Management",
    "Sri Aravinda Industrial Training Center (Sanjaynagar Doddaballapur)",
    "Sri Aurbindo First Grade College for Women",
    "Sri Ayyappan ITI (Jayamahal)",
    "Sri Banashankari ITI",
    "Sri Banashankari ITI",
    "Sri Basavaraja Swamy College of Nursing",
    "Sri Basaveshwara First Grade College For Women(Nelamangala)",
    "Sri Chamarajendra Samskrita College",
    "Sri Devaraj Urs Institute of Management",
    "Sri Jayachamarajendra(Govt)Polytechnic",
    "Sri Jayadeva Institute of Physiotherapy (Gurappanapalya)",
    "Sri K Shivaram Industrial Training Centre (Ramamurthynagar)",
    "Sri Kalabhyraveshwara Swamy College of Nursing",
    "Sri Kalabyreshwara Ayurvedic Medical College",
    "Sri Kongadiayappa College",
    "Sri Kongadiayappa College of Education",
    "Sri Krishana Institute of Technology",
    "Sri Krishna College of Education B Ed(Devanahalli)",
    "Sri Krishna College of Nursing",
    "Sri Krishna Degree College",
    "Sri Krishna ITI (Devanahalli)",
    "Sri Krishna Polytechnic  (Chikkabellandur)",
    "Sri Krishna Polytechnic (Chikkabanavara)",
    "Sri Krishna Rukmini College of Nursing",
    "Sri Lakshmi College of Management & Science",
    "Sri M Visvesvaraya First Grade College",
    "Sri Mangilal Sundar Bai Gotawat Jain College of Arts & Commerce",
    "Sri Maruthi Degree College",
    "Sri Nirvanaswamy College of Nursing",
    "Sri Raghavendra  College of Nursing",
    "Sri Raghavendra College of Education",
    "Sri Raghavendra College of Pharmacy",
    "Sri Raghavendra ITI (Basaveshwaranagar)",
    "Sri Rajiv Gandhi College of Dental Sciences",
    "Sri Ramakrishna College of Nursing",
    "Sri Revana Siddeshwara Institute  of Technology",
    "Sri Rudreshwara Samskrit College",
    "Sri S Nijalingappa Medical Education Centre (Shivajinagar)",
    "Sri Sadguru Sainath Degree College",
    "Sri Sai College for Women",
    "Sri Sai Ram Degree College",
    "Sri Sairam College of Engineering",
    "Sri Sarvajna college of Education",
    "Sri Sathya Narayana ITI (Herohalli)",
    "Sri Sathya Sai College",
    "Sri Sathya Sai Institute of Higher Medical Sciences",
    "Sri Sathya Sai Institute of Medical Sciences",
    "Sri Sathyanarayana ITI",
    "Sri Shanthini College of Nursing",
    "Sri Shanthini School of Nursing",
    "Sri Sharada First Grade College",
    "Sri Sharada Nursing College (Uttarahalli)",
    "Sri Shivayogi Muneshwaraswamy ITI",
    "Sri Siddagana Arts and Commerce College",
    "Sri Siddaramaiah Law College",
    "Sri Soubhagaya Lalitha College of Nursing",
    "Sri Sri Ayurvedic Medical College",
    "Sri Vagdevi School of Nursing",
    "Sri Veerabhadraswamy ITI",
    "Sri Venkataraju Institute of Management",
    "Sri Venkataraju Institute of Tech",
    "Sri Venkateshwara College of Education",
    "Sri Venkateshwara College of Engineering",
    "Sri Venkateshwara College of Nursing (Peenya)",
    "Sri Venkateshwara College of Science & Management Studies",
    "Sri Venkateshwara Dental College & Hospital (Bannerughatta)",
    "Sri Venkateshwara First Grade College",
    "Sri Venkateshwara Institute of Nursing Sciences (Hongasandra)",
    "Sri Venkateshwara Polytechnic (Bannerghatta)",
    "Sri Venkateshwara School of Nursing",
    "Sri Vidya ITI  (Rajajinagara)",
    "Sri Vidya Vinayaka Institute of Technology (Vinayakanagar)",
    "Sri Vinayaka Para Medical College",
    "Sri Vishnu College of Nursing",
    "Sri Vishnu School of Nursing",
    "Srilakshmi College of Nursing",
    "Srilakshmi College of Nursing (Sunkadakatte)",
    "Srinidhi College of Nursing (Hommadevanahalli)",
    "Srinivasa College of Pharmacy",
    "Srishti Institute of Arts Degree and Technology",
    "Srishti School of Business",
    "SRK School of Nursing",
    "SRN Adarsh Degree College (Chamarajpet)",
    "Srushti College",
    "SS College of Arts & Commerce",
    "SSK Degree College (Chandra Layout)",
    "SSR College of Science &  Commerce",
    "SSR College of Science & Management Studies",
    "St Aloysius Degree College (Coxtown)",
    "St Annes  Degree College For Women (Halasur)",
    "St Annes Frist Grade College For Women (Ramamurthy Nagar)",
    "St Anns First Grade College for Women",
    "St Claret College",
    "St Francis B Ed College",
    "St Francis de Sales College (PG)",
    "St George College of Management",
    "St George College of Nursing",
    "St George School of Nursing",
    "St Hopkins College of Management (Adugodi)",
    "St Hopkins International College (Kalyana Nagara)",
    "St Jeromes First Grade College (Carmelaram)",
    "St John’s College of Pharmacy",
    "St John’s College of Physiotherapy",
    "St John's College  of Management",
    "St John's College of Nursing",
    "St John's Institute of Nursing",
    "St John's Medical College & Hospital",
    "St John's Medical College (Madivala Checkpost)",
    "St John's Medical College (RDT)",
    "St John's Medical College",
    "St John's School of Nursing",
    "St Joseph Nursing School Madiwala",
    "St Josephs Arts & Science College",
    "St Josephs College of Commerce",
    "St Josephs College of Law",
    "St Joseph's Institute of Management",
    "St Martha's Hospital School of Nursing",
    "St Mary School of Nursing",
    "St Mary’s Institute of Nursing",
    "St Marys School Of Nursing",
    "St Patricks Industrial Training Centre (Brigade Road)",
    "St Pauls College (Nelagadaranahalli)",
    "St Paul's College of Education",
    "St Philomena's First Grade College",
    "St Philomena's Hospital",
    "St Philomina's College of Nursing",
    "St Teresas Degree College for Women (Royan Circle Chamarajpete)",
    "St Teresas Womens Teachers Training institute",
    "St Theresa Institute of Management",
    "St Theresa School of Nursing",
    "St Theresa's Women's Teacher's Training \nInstitute",
    "St Vincent Pallotti Degree College",
    "Subramanya College of Education",
    "Surana College (South End)",
    "Surana College(Peenya)",
    "Surarna College  (Kengeri)",
    "Surya College of Nursing",
    "Surya Nursing School",
    "Sushruta School of Nursing",
    "Sushrutha Ayurvedic Medical College",
    "Sushrutha Institute of Nursing",
    "Sushrutha School of Nursing",
    "SVCK ITI (Thyagarajanagara)",
    "SVN College of Nursing Gayathrinagar",
    "SVR College of Commerce & Management Studies",
    "Swamy Narayan Institute of Science & Management",
    "Swamy Vivekananda College of Nursing",
    "Swamy Vivekananda Rural First Grade College",
    "Swamy Vivekananda(Pvt)ITI",
    "Symbiosis Institute of Business Management Bangalore",
    "Symbiosis School of Media and CommunicationBangalore",
    "T E S Polytechnic",
    "T John College",
    "T John College of Nursing",
    "T John College of Pharmacy",
    "T John Institute of Management & Science",
    "T John Institute of Technology",
    "TASMAC College",
    "Teachers Academy Degree College (Kalyan Nagar)",
    "Teachers Academy Group Of Institutions",
    "Teachers Law College",
    "The Apparel Training And Design Centre",
    "The Association Of People with Desiblity",
    "The Bangalore Social & Educational Institute Of Management Studies",
    "The Capitol College of Nursing",
    "The Capitol School of Nursing",
    "The East Point College of  Higher Education",
    "The Karnataka College of Nursing",
    "The Kingdom College",
    "The Oxford College of Business Management",
    "The Oxford College of Education",
    "The Oxford College of Engineering",
    "The Oxford College of Hotel Management",
    "The Oxford College of Law (HSR Layout)",
    "The Oxford College of Nursing",
    "The Oxford College of Pharmacy",
    "The Oxford College of Physiotherapy",
    "The Oxford College of Science",
    "The Oxford Dental College",
    "The Oxford Medical College Hospital  Research Center",
    "The Oxford Polytechnic",
    "The Regency College of Education",
    "The Richmond Psychosocial and Rehablitation",
    "Tirumala College of Commerce & Business Management",
    "Trisha College Commerce and Management",
    "Triveni Institute of Commerce and Management",
    "United Degree College",
    "United Mission Degree College",
    "Universal College of Commerce",
    "Universal College of Computer Application",
    "Universal College of Nursing",
    "Universal School Of Administration",
    "Universal School Of Nursing",
    "University College of Physical Education",
    "University Law College",
    "University of Agriculture sciences (GKVK)",
    "University Vishweshwaraya College of Engineering",
    "US Business School Degree College",
    "V E T B V L Polytechnic",
    "V H D Central Institute of Home Science",
    "V S S College of Nursing",
    "V S S School Of Nursing",
    "Vagdevi College Of Nursing",
    "Vagdevi Degree College",
    "Vagdevi Nursing School",
    "Vagdevi Vilas College",
    "Valley School Of Nursing",
    "Varalakshmi Hospital College of Nursing",
    "Varalakshmi School Of Nursing",
    "Vasavi Gnanapeeta Polytechnic",
    "Vasavi Institute of Management & Advanced Studies",
    "Vasavi Jnanapeeta First Grade College",
    "Vedantha College PU & Degree",
    "Veerayoga institute of allied health sciences",
    "VEIT Degree College",
    "Vemana Institute of Technology",
    "VET First Grade College",
    "Veterinary College Bangalore",
    "Vidhya Vahini first grade college",
    "Vidya Sagar First Grade College",
    "Vidya Sanskar Instiute of Science",
    "Vidya Sri Private ITI",
    "Vidya Vardhaka Sangha First Grade College",
    "Vidya Vikas Polytechnic",
    "Vidyakirana Institute of Nursing Sciences",
    "Vidyakirana School Of Nursing",
    "Vidyashree ITI",
    "Vidyashree Pvt ITI",
    "Vidyavana First Grade College",
    "Vignan Institute Of Nursing",
    "Vijaya College",
    "Vijaya College  (R V Road)",
    "Vijaya First Grade College (Devanahalli)",
    "Vijaya Teachers College",
    "Vijaya Vittal Institute of Technology",
    "Vijayanagar College of Nursing",
    "Vijayanagar School of Nursing",
    "Vishveshwaraiah Technological University Regional Office, Bangalore",
    "Vishveswarapura Law College",
    "Vishwa Chethana Degree College",
    "Vishwabharathi School of Nursing",
    "Vishwasai College of Nursing",
    "Vision Degree College",
    "Viswa Sai School Of Nursing",
    "Vittal Malya Scientific Research Foundation",
    "Vittala International Institute of Ophthalmology",
    "Vivek ITI",
    "Vivekananada ITI (Ramanagar)",
    "Vivekananda College of Arts Science and Commerce",
    "Vivekananda College of Education",
    "Vivekananda College of Law",
    "Vivekananda College of Pharmacy",
    "Vivekananda Degree College for Women",
    "Vivekananda Institute of Management",
    "Vivekananda Institute of Technology",
    "Vivekananda ITI (Harohalli)",
    "Vogue Institute of Fashion Technology",
    "Vokkaligara Sanga Dental College & Hospital",
    "Vokkaligara Sangha ITC",
    "VTU  Extension  Center (Karnataka State Remote Sensing Application Centre)",
    "VTU  Extension  Centre (United Technologies Ltd )",
    "VTU Extension Center (BMS College of Engineering)",
    "VTU Extension Centre (IR Rasta)",
    "VTU Extension centre (Reva Institute of Technology & Management)",
    "VV Pura Institute of Pharmaceutical Sciences",
    "VV Puram Arts and commerce college",
    "VV Puram Science college",
    "VVN Degree College",
    "VVN Instiute of Management  & Technology",
    "Vydehi Institute of biotech science",
    "Vydehi Institute of Dental Sciences & Research Centre",
    "Vydehi Institute of Medical Sciences",
    "Vydehi Institute of Nursing Sciences & Research Centre",
    "Westline College of Commerce Management and Science",
    "Williams International College",
    "Wochardt Institute of Medical",
    "Wockhardt Institute of Nursing",
    "Xavier Institute of Management & Entrepreneurship",
    "Yadava Degree College",
    "Yellamma Dasappa Institute of Technology",
    "YMCA College of Physical Education"
  ];

  // Filter universities based on search term
  const filteredUniversities = universities.filter(university => 
    university.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // Handle click outside dropdown to close it
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsDropdownOpen(false);
      }
    }
    
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    
    try {
      // First check if this email or phone already exists in the waitlist
      const { data: existingEntries, error: checkError } = await supabase
        .from('student_waitlist')
        .select('id')
        .or(`email.eq.${formData.email},phone.eq.${formData.phone}`);

      if (checkError) throw checkError;

      // If we found existing entries, handle as already registered
      if (existingEntries && existingEntries.length > 0) {
        setIsAlreadyRegistered(true);
        setTimeout(() => {
          navigate('/');
        }, 3000);
      } else {
        // If not already registered, proceed with insertion
        const { error: insertError } = await supabase
          .from('student_waitlist')
          .insert([
            {
              name: formData.name,
              email: formData.email,
              phone: formData.phone,
              university: formData.university,
            }
          ]);
  
        if (insertError) throw insertError;
  
        setSuccess(true);
        setTimeout(() => {
          navigate('/');
        }, 3000);
      }
    } catch (err) {
      // Handle PostgreSQL unique constraint violation (code 23505)
      if (err.code === '23505') {
        setIsAlreadyRegistered(true);
        setTimeout(() => {
          navigate('/');
        }, 3000);
      } else {
        setError(err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };
  
  // Handle university selection
  const handleUniversitySelect = (university: string) => {
    setFormData(prev => ({ ...prev, university }));
    setSearchTerm('');
    setIsDropdownOpen(false);
  };

  // Clear selected university
  const clearUniversity = () => {
    setFormData(prev => ({ ...prev, university: '' }));
  };

  return (
    <div className="min-h-screen pt-16 bg-black">
      <div className="absolute inset-0">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#00FF0015_1px,transparent_1px)] bg-[size:100px] bg-[position:center] animated-grid after:content-[''] after:absolute after:inset-0 after:bg-[linear-gradient(to_bottom,#00FF0015_1px,transparent_1px)] after:bg-[size:100px] after:bg-[position:center]">
          <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"></div>
        </div>
      </div>
      <div className="relative max-w-md mx-auto px-4 py-12">
        <Link to="/" className="inline-flex items-center text-gray-400 hover:text-white mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="bg-white/5 backdrop-blur-lg rounded-xl p-8 border border-neon-green/20"
        >
          <h2 className="text-2xl font-bold text-white mb-6 text-center">Submit Waitlist</h2>
          {success ? (
            <div className="text-center">
              <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4 mb-4">
                <p className="text-green-500">Thank you for joining our waitlist!</p>
                <p className="text-gray-400 text-sm mt-2">
                  We'll notify you when we launch. Redirecting to home page...
                </p>
              </div>
            </div>
          ) : isAlreadyRegistered ? (
            <div className="text-center">
              <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 mb-4">
                <p className="text-blue-500">You are already in the waitlist.</p>
                <p className="text-gray-400 text-sm mt-2">
                  Redirecting to home page...
                </p>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-gray-300 mb-1">
                  Full Name
                </label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                  <input
                    id="name"
                    name="name"
                    type="text"
                    value={formData.name}
                    onChange={handleChange}
                    className="w-full pl-10 pr-4 py-2 bg-white/5 border border-neon-green/20 rounded-lg text-white focus:border-neon-green/40 focus:outline-none focus:ring-1 focus:ring-neon-green/40"
                    placeholder="Enter your full name"
                    required
                  />
                </div>
              </div>
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-300 mb-1">
                  Email Address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                  <input
                    id="email"
                    name="email"
                    type="email"
                    value={formData.email}
                    onChange={handleChange}
                    className="w-full pl-10 pr-4 py-2 bg-white/5 border border-neon-green/20 rounded-lg text-white focus:border-neon-green/40 focus:outline-none focus:ring-1 focus:ring-neon-green/40"
                    placeholder="Enter your email address"
                    required
                  />
                </div>
              </div>
              <div>
                <label htmlFor="phone" className="block text-sm font-medium text-gray-300 mb-1">
                  Phone Number
                </label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                  <input
                    id="phone"
                    name="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={handleChange}
                    className="w-full pl-10 pr-4 py-2 bg-white/5 border border-neon-green/20 rounded-lg text-white focus:border-neon-green/40 focus:outline-none focus:ring-1 focus:ring-neon-green/40"
                    placeholder="Enter your phone number"
                    required
                  />
                </div>
              </div>
              <div>
                <label htmlFor="university" className="block text-sm font-medium text-gray-300 mb-1">
                  University/College
                </label>
                <div className="relative" ref={dropdownRef}>
                  <School className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                  
                  {formData.university ? (
                    <div className="w-full pl-10 pr-10 py-2 bg-white/5 border border-neon-green/20 rounded-lg text-white flex items-center justify-between">
                      <div className="text-white truncate">{formData.university}</div>
                      <button 
                        type="button" 
                        onClick={clearUniversity}
                        className="text-gray-400 hover:text-white absolute right-3 top-1/2 transform -translate-y-1/2"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>
                  ) : (
                    <div 
                      onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                      className="w-full pl-10 pr-4 py-2 bg-white/5 border border-neon-green/20 rounded-lg text-white cursor-pointer flex items-center justify-between"
                    >
                      <span className="text-gray-400">Select your university/college</span>
                      <svg className="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                      </svg>
                    </div>
                  )}
                  
                  {isDropdownOpen && (
                    <div className="absolute z-10 mt-1 w-full bg-black/80 backdrop-blur-md border border-neon-green/20 rounded-lg shadow-lg max-h-60 overflow-auto scrollbar-hide">
                      <div className="sticky top-0 bg-black/90 p-2">
                        <div className="relative">
                          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                          <input
                            type="text"
                            placeholder="Search universities..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="w-full pl-9 pr-4 py-2 bg-white/5 border border-neon-green/20 rounded-lg text-white text-sm focus:border-neon-green/40 focus:outline-none focus:ring-1 focus:ring-neon-green/40"
                          />
                        </div>
                      </div>
                      <div className="py-1">
                        {filteredUniversities.length === 0 ? (
                          <div className="text-gray-400 p-3 text-sm text-center">No universities found</div>
                        ) : (
                          filteredUniversities.map((university, index) => (
                            <div
                              key={index}
                              className="px-4 py-2 text-sm text-white hover:bg-neon-green/10 cursor-pointer truncate"
                              onClick={() => handleUniversitySelect(university)}
                            >
                              {university}
                            </div>
                          ))
                        )}
                      </div>
                    </div>
                  )}
                </div>
                <input 
                  type="hidden" 
                  name="university" 
                  value={formData.university} 
                  required 
                />
              </div>
              {error && (
                <div className="text-red-500 text-sm bg-red-500/10 border border-red-500/20 rounded-lg p-3">
                  {error}
                </div>
              )}
              <button
                type="submit"
                disabled={loading}
                className="w-full py-3 bg-neon-green text-black rounded-lg font-semibold hover:bg-[#00CC00] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading ? 'Submitting...' : 'Join Waitlist'}
              </button>
            </form>
          )}
        </motion.div>
      </div>
    </div>
  );
};

export default WaitlistForm;